apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: chatai-app-ebs-retain-sc # You can name it anything you like
allowVolumeExpansion: true 
provisioner: ebs.csi.aws.com # For CSI driver
parameters:
  type: gp3 # Or gp2, io1, etc. based on your needs
  fsType: ext4
reclaimPolicy: Retain # <-- THIS IS THE IMPORTANT PART FOR DATA PROTECTION
volumeBindingMode: WaitForFirstConsumer # Recommended for EBS