apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-mmh-sg-lbc-chart-aws-load-balancer-controller-role
  labels:
    app.kubernetes.io/instance: eks-mmh-sg-lbc-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.13.2 # This will be updated later
    helm.sh/chart: aws-load-balancer-controller-1.13.2 # This will be updated later
rules:
# --- THIS IS THE NEW RULE YOU ARE ADDING ---
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# --- END OF NEW RULE ---
- apiGroups:
  - elbv2.k8s.aws
  resources:
  - targetgroupbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elbv2.k8s.aws
  resources:
  - ingressclassparams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - extensions
  - networking.k8s.io
  resources:
  - services
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - delete
  - create
  - update
- apiGroups:
  - elbv2.k8s.aws
  - ""
  - extensions
  - networking.k8s.io
  resources:
  - targetgroupbindings/status
  - pods/status
  - services/status
  - ingresses/status
  verbs:
  - update
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.k8s.aws
  resources:
  - loadbalancerconfigurations
  - targetgroupconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.k8s.aws
  resources:
  - loadbalancerconfigurations/finalizers
  - targetgroupconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.k8s.aws
  resources:
  - loadbalancerconfigurations/status
  - targetgroupconfigurations/status
  verbs:
  - get
  - patch
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/finalizers
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - grpcroutes
  - httproutes
  - tcproutes
  - tlsroutes
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - grpcroutes/finalizers
  - httproutes/finalizers
  - tcproutes/finalizers
  - tlsroutes/finalizers
  - udproutes/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - grpcroutes/status
  - httproutes/status
  - tcproutes/status
  - tlsroutes/status
  - udproutes/status
  verbs:
  - get
  - patch
  - update